apiVersion: skaffold/v1beta10
kind: Config
build:
  tagPolicy:
    sha256: {}
    # artifacts:
    # - image: gcr.io/k8s-skaffold/skaffold-helm
deploy:
  # kubectl:
  #   manifests:
  #     - volumes/nfs-pv.yaml
  #     - volumes/nfs-claim.yaml
  #     - volumes/plex-config-pv.yaml
  #   flags:
  #     global:
  #       - "-n plex"
  helm:
    releases:
    - name: plex
      namespace: plex
      chartPath: kube-plex/charts/kube-plex
      #wait: true
      #valuesFiles:
      #- helm-skaffold-values.yaml
      overrides:
        image:
          repository: linuxserver/plex
          tag: arm32v7-latest
        claimToken: claim-Fk7YkZqveq9eyCBMj6HA
        persistence:
          data:
            claimName: nfs-claim1
          config:
            size: 2Gi
        kubePlex:
          image:
            repository: yoshwata/kube-plex_linux_arm7l
        service:
          type: ClusterIP
          externalIPs:
            - 192.168.1.12
        volume:
          server: 192.168.1.12
      #recreatePods will pass --recreate-pods to helm upgrade
      #recreatePods: true
      #overrides builds an override values.yaml file to run with the helm deploy
      #overrides:
      # some:
      #   key: someValue
      #setValues get appended to the helm deploy with --set.
      #setValues:
        #some.key: someValue
