apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: screwdrivercd_screwdriver
    sync:
      manual:
      - src: 'screwdriver/**/*.*'
        dest: /usr/src/app/node_modules/screwdriver-api
        strip: screwdriver/
deploy:
  # kubectl:
  #   manifests:
  #     - volumes/nfs-pv.yaml
  #     - volumes/nfs-claim.yaml
  #     - volumes/plex-config-pv.yaml
  #   flags:
  #     global:
  #       - "-n plex"
  helm:
    releases:
    - name: screwdriver-cd
      namespace: test-screwdriver
      chartPath: screwdriver-chart
      #wait: true
      #valuesFiles:
      #- helm-skaffold-values.yaml
      values:
        image: screwdrivercd_screwdriver
      overrides:
        api:
          externalIPs: 172.21.110.170
          # image: screwdrivercd/screwdriver:latest
          # image: yoshwata/screwdrivercd_screwdriver:2bbd73d-dirty
          # image: "yoshwata/screwdrivercd_screwdriver:{{ .Values.image.tag }}"
        ui:
          image: screwdrivercd/ui:latest
        store:
          image: screwdrivercd/store:latest
        launcher:
          version: latest
        ingress:
          hosts:
            api: dev.yoshwata.k3s.master001.ssk.ynwm.yahoo.co.jp
            ui: dev.yoshwata.k3s.master001.ssk.ynwm.yahoo.co.jp
            store: dev.yoshwata.k3s.master001.ssk.ynwm.yahoo.co.jp
      imageStrategy:
        helm: {}
      #recreatePods will pass --recreate-pods to helm upgrade
      #recreatePods: true
      #overrides builds an override values.yaml file to run with the helm deploy
      #overrides:
      # some:
      #   key: someValue
      #setValues get appended to the helm deploy with --set.
      #setValues:
        #some.key: someValue
